
project_id = "wskiwwfgelypkrufsimz"

[api]
enabled = true
[auth]
enabled = true
[realtime]
enabled = true

[functions.manage-dealer-postcode]
verify_jwt = true

[functions.migrate-car-organizations]
verify_jwt = true
