
project_id = "wskiwwfgelypkrufsimz"

[api]
enabled = true
port = 8080
schemas = ["public", "storage", "graphql_public"]

[db]
port = 5432

[studio]
enabled = true
port = 3000

[inbucket]
enabled = true
port = 4000

[functions]
[functions.car-dealer-scraper]
verify_jwt = false

[functions.cazoo]
verify_jwt = false

[realtime]
enabled = true
