
project_id = "wskiwwfgelypkrufsimz"

[api]
enabled = true
[auth]
enabled = true
[realtime]
enabled = true

[functions.manage-dealer-postcode]
verify_jwt = true

[functions.generate-api-key]
verify_jwt = false

[functions.populate-car-data]
verify_jwt = false
