
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wskiwwfgelypkrufsimz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indza2l3d2ZnZWx5cGtydWZzaW16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNDQ4NjEsImV4cCI6MjA1NzcyMDg2MX0.xGojh6R7eyfpzfHTeaNvFCDCZwxqGDiGNJKulf4XYEc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Set your MapBox public token here
// This will be replaced with the value from Supabase secrets
export const MAPBOX_TOKEN = import.meta.env.VITE_MAPBOX_TOKEN || 'YOUR_MAPBOX_TOKEN';
